### ISSUE TITLE
Data lost after RK usage on NK3 AM

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-3-firmware#123] opened 2022-11-28 14:18 UTC
User reports, that RK feature use on NK 3 AM causes data lost.

> ssh-add -K returned 

>     Provider "internal" returned failure -1
>     Unable to load resident keys: invalid format

> 1. Tried to delete the resident key with chromium, just to learn there is no PIN setup, but he is sure he did setup a pin weeks ago
> 2. Added a new pin and tried to login to github but it didnt work
> 3. Reinstalled the firmware and the x5c bug occurs when testing

**Comment by robin-nitrokey** [comment] 2023-02-14 20:32
The root cause for this issue will be fixed in the next release, see https://github.com/Nitrokey/nitrokey-3-firmware/pull/160.

**Closed by robin-nitrokey** 2023-02-14 20:32 UTC
Labels: bug
